version: "3"

services:
  api:
    tty: true
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file: .env
    volumes:
      - ./backend/src:/app
      - ./data/public:/var/data/public
      - ./data/static:/var/data/static
      - ./data/media:/var/data/media
    ports:
      - 8000:8000
      
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
