FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    python3-pip \
    python3-cffi \
    python3-brotli \
    libpango-1.0-0 \
    libharfbuzz0b \
    libpangoft2-1.0-0 \
    gettext \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./check-postgres.py /tmp/check-postgres.py
RUN chmod a+x /tmp/check-postgres.py

 # Copy the current directory contents into the container at /app
COPY src/ .

EXPOSE 8000

CMD bash -c "python /tmp/check-postgres.py && python manage.py runserver 0.0.0.0:8000"
