# Generated by Django 4.1.5 on 2024-11-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
    ]
